### ISSUE TITLE
5.10 kernel compatibility

### ISSUE THREAD

**Issue by kdoren** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#11]
Thanks very much for your work on this.

I tried making a 5.10.46 kernel (for raspberry pi) using the files from branch v5.12-sound-master (I simply replaced all the files under sound/usb/ with the ones here.

The kernel build succeeded, and qasmixer presented the controls (for 6i6 gen2 and 18i20 gen3).

However, jack audio was not able to open an alsa driver for scarlett devices (it could to other devices).
So it seems that there is something in the 5.12 scarlett code that is incompatible with 5,10.  Or maybe I need to replace more files than just the ones under sound/usb.

Do you have any suggestions as to what needs to change to backport to 5.10?   or best way to debug?

Thanks,
Kevin

```
Jul  5 04:09:24 jambox jackdrc[1217]: creating alsa driver ...hw:CARD=USB,DEV=0|hw:CARD=USB,DEV=0|64|4|48000|0|0|nomon|swmeter|-|16bit
Jul  5 04:09:24 jambox jackdrc[1217]: ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Jul  5 04:09:24 jambox jackdrc[1217]: Jack: JackDriver::Close
```

**Comment by HinTak** [comment]
You don't need to build a whole kernel - you could just use the stock raspberrypi pi kernel packages, build and copy the new kernel modules into /lib/modules/5.10.../updates, run depmod and reboot. You can switch back to the old usb sound modules as shipped by the raspberrypi folks, by removing the new ones in /lib/.../updates.

Since there is no indication that your jack setup works with the as-shipped raspberrypi kernel packages, I am going to close this now. You should first try to fix problem with your jack setup without using the code here.

**Comment by kdoren** [comment]
I build my own kernels to get different kernel configs (low-latency PREEMPT, and 1000Hz timers.
I have previously had same jack config

**Comment by HinTak** [comment]
Get your setup to work with the as-shipped raspberrypi kernel packages first.

**Comment by kdoren** [comment]
There are many hundreds of people using my kernel builds for jack audio with USB interfaces on raspberry pi.
Are you sure 5.12 sound/usb files should be compatible with 5.10?

**Comment by HinTak** [comment]
I have a raspberrypi right in front of me. It should build 6 *.ko's. You should copy all 6 into .../updates, although the two important ones are snd-usb-audio.ko and snd-usbmidi-lib.ko. 

Now, please go and start from the as-shipped raspberrypi kernel packages and fix your jack usage problem first, before attempting to use the code here.

**Comment by HinTak** [comment]
See https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/commit/70e8914c49b8c9bd16e71a2fae967738bed0406b possibly, but I am not convinced your problem is that - that's accompanied by piles of kernel messages and stalls, and a lot more visible that just "my jack setup does not work".

**Comment by drc0** [comment]
Hello, I compiled v5.12-sound-master f68c4999761eff8f12951cdff74ccd4bb2dc41d6 against debian 5.10.0-13-amd64 kernel, now alsamixer can see all the controls but the sound card doesn't shows up under pulseaudio so no output is usable, is it a known bug?

**Comment by HinTak** [comment]
Avoid indirections like pulseaudio when you try to debug. Get it work with aplay/arecord first.
