### ISSUE TITLE
18i8 Scarlett - This card can't output sound. But, the proprietary options apears and works for Alsamixer

### ISSUE THREAD

**Issue by mikefaille** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#3]
I'm able to install the driver without issue. 
I use the branch `v5.11-scarlett-gen3` and I configure the module with those options : 
```
options snd_usb_audio device_setup=1,1,1,1
options snd_usb_audio vid=0x1235 pid=0x8210 device_setup=1
options snd_usb_audio vid=0x1235 pid=0x8211 device_setup=1
options snd_usb_audio vid=0x1235 pid=0x8212 device_setup=1
options snd_usb_audio vid=0x1235 pid=0x8213 device_setup=1
options snd_usb_audio vid=0x1235 pid=0x8214 device_setup=1
options snd_usb_audio vid=0x1235 pid=0x8215 device_setup=1
```

Without this driver, it works perfectly after configuring the sound card using Windows 10 + VMWARE then after using the device under Linux.

With the patched module, I also tried to configure the sound card under windows with a basic configuration under Linux using Jack and it doesn't work.

My kernel version : 
`Linux pop-os 5.11.0-7614-generic #15~1618626693~21.04~ecb25cd-Ubuntu SMP Thu Apr 22 15:59:53 UTC  x86_64 x86_64 x86_64 GNU/Linux`

The git hash used for this module : b8023785a39bb8f47066bc1fbc4b2b57ce4ff15a
Branch : v5.11-scarlett-gen3

Here is my alsa config if it could be usefull : 

![Screenshot from 2021-05-16 13-03-23](https://user-images.githubusercontent.com/978196/118410978-23884b00-b647-11eb-8a48-271a1ccbb731.png)

Here is my Jack configuration  : 
![Screenshot from 2021-05-16 13-05-47](https://user-images.githubusercontent.com/978196/118411033-8548b500-b647-11eb-9908-dae90a2ab78b.png)

**Comment by HinTak** [comment]
@mikefaille @sadko4u I have managed to move this issue to the split out scarlett sound-usb kernel-module repo (you should get notification of this message from the new location); and I have merged all the debug code into here too - found one bug with the debug version of the driver ( https://github.com/sadko4u/focusrite-scarlett-backports/issues/8 )
and one bug with the production version of the driver while merging ( https://github.com/sadko4u/focusrite-scarlett-backports/pull/2 is in the debug version but https://github.com/sadko4u/focusrite-scarlett-backports/pull/3 is not yet in the production version) . I don't know if either are important, since I don't have the hardware, but the current state of this repo should be better than either now.

To enable debugging, insert a single line "#define DEBUG 1" at the top of  `sound/usb/mixer_scarlett_gen2.c` before compiling.

@sadko4u having looked at the debug code, yes, I think they should be removed completely before submitting upstream. Also, many of the statements are simply about reaching specific routines or specific points in the code, and can be replace by the generic `usb_audio_info(mixer->chip, __FUNCTION__);` or  `usb_audio_info(mixer->chip, "%s  line %d", __FUNCTION__, __LINE__);` etc - I think writing them in these ways would make it more obvious they are debug only, as well as easier to ignore for being generic too. Changing them to `usb_audio_dbg()` would automatically enable dynamic debugging on systems where dynamic debugging is available; but anyway, I think most of them should be removed completely in the long term rather than converted from `usb_audio_info` to `usb_audio_dbg`.

**Comment by HinTak** [comment]
I have updated the 'v5.12-sound-master' branch as the default, which also contains two post-submission fixes (one for 18i8 gen 3). People should use that branch now.

It sounds like the code submitted upstream + the recent fixes should address this? Anyway, the sound master branch is tracking what is in the sound maintainer's tree, and probably should be used until / unless there is any substantial further work to be included.

**Comment by geoffreybennett** [comment]
> "It sounds like the code submitted upstream + the recent fixes should address this?"
I'm not sure if there is anything to fix. When you turn Speaker Switching Off, the global mute is activated (this is normal behaviour as per the Focusrite manual) and you need to deactivate the mute using alsamixer/qasmixer or using the mute button on the interface (18i20 only). It is very confusing for the 18i8 because there is no physical mute button/indicator.

@mikefaille The screenshot from your video shows the global mute on (4th column, 5th item). If you switch the mute off then sound should work again. Can you confirm that this works with the latest driver?

**Comment by HinTak** [comment]
The ".pad_input_count = 4" (from 2) post-submission change is specifically said to affect 18i8 - what is the effect of not having it?

**Comment by HinTak** [comment]
I see Takashi had commented on the index.id issue, and upstream had a little correction on it. Anyway, unless we have big upcoming changes we should try to use backported upstream and hopefully see / fix any further issues.

**Comment by geoffreybennett** [comment]
> The ".pad_input_count = 4" (from 2) post-submission change is specifically said to affect 18i8 - what is the effect of not having it?

Not having it means that the third and fourth pad controls are missing.

**Comment by geoffreybennett** [comment]
> I see Takashi had commented on the index.id issue, and upstream had a little correction on it.

I don't know what the "index.id issue" is, and I can't find a message from Takashi about it. Can you clarify?

**Comment by HinTak** [comment]
Sorry I meant https://mailman.alsa-project.org/pipermail/alsa-devel/2021-June/186606.html , which was partly added afterwards in https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/commit/8120b7e64ad42a50fe8f7d7705ecee469d21be7b

**Comment by HinTak** [comment]
Please feel free to continue the exchange, but I am closing this issue now, as the original problem seems to have gone.

**Comment by geoffreybennett** [comment]
> Sorry I meant https://mailman.alsa-project.org/pipermail/alsa-devel/2021-June/186606.html , which was partly added afterwards in [8120b7e](https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/commit/8120b7e64ad42a50fe8f7d7705ecee469d21be7b)

Oh, right. Yes, that was in the set of patches I already submitted upstream:
https://github.com/geoffreybennett/scarlett-gen2/commit/9ba38e3006b0ecc997c4357e5664389a211211f4
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=785b6f29a795f109685f286b91e0250c206fbffb

**Comment by HinTak** [comment]
The sound/usb part of 5.14-rc1 continues to only need a one line change (https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module/commit/3c0afbcf535c741d5cfd71f456f99261a431c246) to be built against 5.12, so hopefully we should get more widespread testing of the new code .
